/*  GIMP header image file format (RGB): D:\Dokumenty\Moje dokumenty\test_image.h  */

#define width 64
#define height 32

/*  Call this macro repeatedly.  After each use, the pixel 
data can be extracted  */

#define HEADER_PIXEL(data,pixel) {\
pixel[0] = (((data[0] - 33) << 2) | ((data[1] - 33) >> 4)); \
pixel[1] = ((((data[1] - 33) & 0xF) << 4) | ((data[2] - 33) >> 2)); \
pixel[2] = ((((data[2] - 33) & 0x3) << 6) | ((data[3] - 33))); \
data += 4; \
}
static const char const *header_data =
	"!!!!!1%!!!%\"!1!!$!U-*35G.$-U0D]_3%B)5&\"16F:786V>9W.D;'BI<7VN=H*S"
	">X>X?XR\\A(^`B)3%BYC)CYO,DY[0EZ/3F:;7G:G:H*S>HZ_@IK+DJ;;FK+CIK[OL"
	"LK[OM<'QN,3UNL;WO,GYO\\O\\PLW^Q-$!Q],$R=4&RM@(S=H*T-P-TM\\.U.$1UN,3"
	"V>86V^@8W>H9WNL;X>X=X^\\@Y/(BY_0DZ?4EZO@G[?HI[OLK\\/TM\\O\\O]/`Q]P,S"
	"!1!!!!!\"!!%!!Q-$'2I:+SML/4EZ1U.$3UN,5F.47FJ;8W\"@:7:F;WNK=(\"P>(2V"
	"?8FZ@8V^A9'\"B97&C9G*D9S.E*#1F*/4FZ?8GJK<HJW>I;#AJ+3EJ[;HK;GJL+WN"
	"L[_PM<+SN<3UN\\?XOLG[P,S]P\\__Q=(\"R-0%R=<'S-D*S]P+T-T-T]\\0U>(2U^04"
	"VN<7W.@9W>L:X.P<XNX>Y.`@Y?(CY_0EZ?8GZ_@H[?LJ[_PL\\?XM\\_`P]@$R]`,T"
	"!!!\"!1%\"!!!\"#QM,)C)C-T-S04Y_2E:'4U^06F:78&R=9G*D;'>I<7VN=H&S>H>X"
	"?XN[@X^`AY/%BY?(CIO,DI[/EJ+3F:;6G:G:H*S<HJ_@IK+CJ;7FJ[CIKKOLL;[O"
	"M<'RM\\/TNL7VO,CYOLO\\P<[_P]$!QM,#R-8&R]@'SMH*S]P,TM\\.U.$1UN,3V.45"
	"VN<8W.D9WNP<X>X>XN`?Y?$AYO0DZ/4EZO<G[/DI[OLK\\/TM\\OXO]0$P]@(R]`0T"
	"!1!!!1%\"\"!1$&R=8+SML/$EY1E*\"3EN,5V*376F:8V^@:'6F;GJK<W^P>(2U?(FY"
	"@8V^A9'!B97&C9G)D)S-E*#1F*34FJ?8GJK;H:W>I;'AI[3DJK?HK;GKL+SML[_P"
	"ML+RN,3VN\\?XOLKZP,S]PL_`Q=(\"Q]0$RM<'S-@)SML+T=T-T]\\/U>(2U^04V>86"
	"W.D8W>H;X.T<X>X>X^`AYO(CZ/0EZO8FZ_@H[?HJ[_LL\\?XM\\O`O]0(Q]P,S^00U"
	"!1!!!!%\"#1A*)C)C-D)S04U]2E:'4EZ/66667VR<9G*C:W>H<'RM=8&R>H:W?HJ\\"
	"@H^`AY/#BI?(CIO,DI[/EJ+3F:76G:G9H*O=HJ_@IK'CJ+7FJ[?IKKOKL;WNM,#Q"
	"M\\/TN<7WO,CYOLO[P<W^Q-#`QM,#R-4%R]@(S=H)T-P,TM\\.U-`1UN,3V.45VN<7"
	"W.D9WNL;X.T=XN\\?Y/$BYO,DZ?4EZO@H[/DI[OHK\\/TM\\O\\N\\_`P]P(S]`0S^@8U"
	"!1!\"\"!1%&\"15+CIK.D=X15&\"3EJ+56*27&B:8VZ?:'2E;GJK<G^O=X.U?(BY@(V]"
	"A9#!B97&C9G)D)S-E)_1F*/4FZ?7GJG;H:W>I+#AI[/DJK;GK;GJL+SMLK[OM<'R"
	"M\\3UN\\?WO<GZP,S\\P\\[_Q-(!Q]0$R=8&S-@)SML+T-T-T]\\0U.(2UN,4V>86V^@8"
	"W>H:W^P<X>X>X^`AY?(BY_0DZ?8FZ_<H[/HJ[OPK\\/XM\\O`P]0(Q]P,S^04U^P8W"
	"!!!!\"A=()\"]@,S]P/TM\\256%45V.6&257FN<97&B:W>G;WRM=8&R>86V?8F[@HZ_"
	"AI+#BI;'CIK+D9[/E:'3F:75FZC9GZO<HJ[@IK'BJ+3FJ[?HKKKKL;WNL\\#QML/S"
	"N<7VN\\?YOLK[P<S]P\\_`QM,\"R-4%RM<'S=D)S]P,T=X.T]`0U>,2U^45VN<7W.@9"
	"W>L:W^T=XN\\?Y.`AYO,BZ/4EZO<G[/DI[?LJ[_TL\\?XN\\_`P]@(R]`0T^04V^P<W"
	"!!!!%\"!2*C=H.45V0T]`35B)5&&26V>88FV?9W.E;'FJ<GZN=X.T>X>X@(R]A)#!"
	"B)3%BY?(CYO-DI_0EJ/4FJ;7G:G:H*W=I+#AI[/CJ;;GK+GJL+OLLK[OM<'RN,3U"
	"NL;WO<GZO\\O\\P<[_Q-(\"Q],#R=4&R]@(S=L*T-T-T]\\/U.$2U^,4V.86V^@8W>D:"
	"W^L<X>X>X^`@Y?(AY_,DZ?8FZO<H[?DJ[OLK\\?TM\\O\\O]0$Q]@(S]`0T^@<V^`@X"
	"\"!1%(2U>,C]P/4E[1U2$45R-5V.47FJ;9'\"A:G:F;WNL=(\"Q>(6U?8FZ@8Z^A9'\""
	"BI7&C9G+D9W.E:'2F*35FZ?9GZO<HJ[?I;#BI[3EJ[?GKKGKL;WML[_PML+SN<7V"
	"N\\?XOLK[P,S]P\\_`Q=(\"R-4%RM<'S-D*S]L+T=X.T]`0U>(2U^45VN87V^D8WNL:"
	"W^T=X>\\?Y.`@Y?,CZ/4EZO<GZ_DH[?LJ[_TL\\?XN\\_`P]@(R]`,T^08U^P<W^`DY"
	"$Q]/*S9G-T1T0TY`3%B)4U^06V:786V>9G.D;'FI<GVN=H*S>X>X?XR\\A(_!AY3$"
	"C)?)CIO,DI[0EZ+4FJ77G:G:H*W>HZ_@I[/DJ;7FK+CIK[OLLK[OM<#QM\\/UNL7W"
	"O<CZO\\O\\PL[_Q-$!Q]0#R=4&R]@(SMH*S]P,TM\\/U.$1UN,3V.85VN<8W.H9WNP;"
	"X>X=XN`@Y/$BY_0DZ/8EZO@H[/HI[OLL\\/TM\\?\\O]0$Q]@,R]`4T^@8V^`@W_0DZ"
	"'RM<,#QN/4EZ1U.$3UN,5V*476F:8V^@:76F;WNL<W^Q>(6U?8FZ@8V^A9'\"B97'"
	"C9G*D9W.E:#1F*34FZC8GZO<HJ[>I;#AJ+/EJ[?HK;GKL+SNL[_PM<+SN,7UN\\?X"
	"O<G[P,W]P\\__Q=(\"R-0$RM8'S=D)SMP,T=X.T]`0U>(2U^44V>86V^@9W>H;X.P<"
	"XNX>X^`AYO,CY_0DZO8GZ_@H[?HK[_PL\\?XN\\_\\O]0$Q]P,S^04V^P<W_0DY_PLZ"
	"*#1D-T)S04Y^2U:'4U^/6F:68&V=9W*C;'BH<7VN=H*S>H>X?XJ[@X^`AY/$BY?("
	"CYK+DY[/EJ+3F:76G:C9H*S=HZ_@IK+CJ;7FJ[CIKKOLL;WOM<'RM\\/TN<;WO,CY"
	"O\\O\\P<W^Q-$!QM0#R-4%R]@'S=H*S]T-TM\\.T^$1UN,3V>46VN<7W.D:W^P;X.T>"
	"XN\\?Y/$AY_,CZ/8EZ_<H[/DI[OLK\\/TM\\OXN]0$Q]@(S]`0T^@4V^P@X_@DZ_PL["
	"+SML/$AY1E*#3UJ+5V*376F98VZ@:76F;GJK<W^P>(2U?8BY@(V]A9'\"B97&C9C)"
	"D9W.E*#1EZ35FZ?8GJK;HJW>I+#AI[/DJ[?HK;GKL+SML[_PML'SN<3VN\\?XO<G["
	"P,S]PL__Q-(\"Q]4$RM<'S-D)SML+T=T.T]`0U>(2U^04V>86V^@8W>H:W^P<XN\\?"
	"X^`AYO,BZ/4DZO8FZ_@H[?HJ[OPL\\?XN\\_\\O]@$R]`,S^04U^P<W^`DX_@HZ_`P\\"
	"-4)S04Q]2E:'4E^066667VR=9G*B:WBH<'RM=8&R>H6W?XN\\@H^`AY/#BY?(CIO,"
	"DI[/E:+2F:76G*C9GZO=HZ[@IK'BJ;3FK+CIKKKKL;[NM,#QML/TN<;VO,CYO\\O\\"
	"P<W^P]#`Q=,#R-8&RM<(S=H*S]P-T=\\/U.$0UN,3V.45VN<7W>D9WNL;X.T>XN\\?"
	"Y?(BYO,CZ/4EZ_@G[/DI[?LK[_TL\\?\\N]/`Q]@(R]`0T^@4V^P<X_0HY_PL[_`T\\"
	".D=W15&\"3EJ+5F&37&B98VZ?:'2E;7FK<WZP=X2T?(BY@(R^A)'\"B)7%C)C)D)S-"
	"E)_1EZ/4FJ?7GJK:H:W>I+#AI[3DJK;GK;GIL+SML[[PM<+RN,3UN\\?XO<GZP,O]"
	"PL[_Q-(!Q]0$R=<'S-@)SML+T-T-TM\\0U>$2U^,4V>86V^@8W>H:X.P<X>\\>X^`@"
	"Y?(BY_0DZ?<GZ_@H[/HJ[OPL\\/TN\\O\\P]0$R]P,S]`4U^@<V_0@Y_PHZ_`P\\`@T]"
	"0$M]25:&45V.66257VN<97&B:W>H<'VM=8&R>H:V?HJ[@HZ_AI/$BI;'CIK+D9[/"
	"EJ+2F:36G*?9GZS<HZ_?IK+BJ;3FJ[CHK[OKL;WNM+_QM\\+TNL7VO,CXOLK[P<W^"
	"P\\_`QM,\"R-4%RM@'S=H)S]P,T=X.T^$0UN(3V.44VN<7W.D9WNH;X.T=XN\\?Y/$A"
	"YO,CZ/4EZO<G[/DI[?LK\\/PM\\OXN\\`$Q]@(R]`,T^@8V^`@W_0DY_@L[`0P]`P\\^"
	"1%&!35F*5&&26VB88FZ?:'2D;7FJ<GZO=X.T?(>X@(N]A)#!B)3%C)C)D)O-DY_1"
	"EJ/4FJ;7G:G;H:S=H[#AI[/DJK7FK;CJL+OML[_PM<'RM\\3UN\\;XO<CZP,S\\PL[_"
	"Q=$!Q]0$R=8'R]@(S=H+T-T-TM\\/U>$2U^,3V.46V^@8W>H:W^P<X>X>X^`@Y?(B"
	"Y_0DZ?4FZ_@H[?HJ[OLK\\?TM\\O\\O]0$Q]P,S^04U^@8V^`@X_@HZ_`L\\`@T^`P\\_"
	"2%2%4%V-6&657FJ;9'\"A:G:G;WNM=8\"R>86V?8FZ@HV_AI+#BI7'CIG*DI[.E*'1"
	"F:35G*?9GZO<HJ[?I;'BJ;3EJ[?HK[KKL;WML[_PML+TN<7VO,CXOLK[P<W^P\\_`"
	"Q=(#Q]4%RM@(S=H*S]P,T=X.T]`1U>(2U^45VN87W.@9WNL;X.T=XN\\?X_$@YO(C"
	"Z/0EZO<G[/@I[?LJ[_TL\\OXN\\_`P]@$Q]`0T^@4V^`<W_0DY_PHZ`0T\\`@X^`P\\_"
	"35F*5&&16V:886V>9W2D;'BJ<GVO=H.T>X>X?XR]A(_!B)3$BYC)CYS,DI_0EZ/4"
	"FJ;7GJG:H*W=HZ_AIK+CJ;;FK+GJK[OMLK[PM<'QN,3TN\\;WO<GYO\\O\\PLW_Q=(\""
	"Q]0$R=8%R]@)SML*T-T,TMX/U>$2U^,3V.45V^@7W>D:W^P<X.X>X^`@Y?(AYO0C"
	"Z?4EZO@H[?DJ[_LK\\/TM\\O\\O\\`$P]P(S^00U^@8W^`@X_@HY_PP[`0T]`P\\_````"
	"4%R-5V.47FJ:9'\"A:7:G;WNK<W^Q>82V?8FZ@8V_A9'\"B97&C9G*D9W.E*'1F*34"
	"FZ?9GZK;H:[?I;'BI[3DJ[?HKKKJL;SNL[_PML+SN,3UN\\CYOLK[P,S]P\\[_Q=(\""
	"Q]0%RM<&S-D)SML,T=X-T]`0U>(2U^04V>87W.@9W>H:W^T<XN\\?Y/$@Y?,BY_0D"
	"ZO8FZ_@I[?HJ[_PL\\/XN\\_`P]@(Q]P0S^@4U^@8W^`DX_PHZ_`P\\`@X^`P`_````"
	"4E^06F:78&R=9G*C;'BI<'RN=H*S>X:X?XN\\@X^`B)/$BY?(CYK+DY_/E:'2FJ;7"
	"G*G:GZS=HZ_@IK+CJ;7FJ[CIK[OLL;WNM<#RM\\/TNL;WO,GYO\\O\\P<[^Q-$!QM,#"
	"R-4&R]<(S=H*S]P-T=\\.U.$1UN,3V.45VN@8W.D9W^L<X.T>X^\\@Y?$BYO0CZ/4E"
	"ZO<H[/DI[OLK\\/TM\\O\\N\\_`Q]@,R^00T^08V^P@W_@HZ_PL[`0T]`@\\^````````"
	"5F.376B98V^@:72F;GJK<W^P>(2U?(BY@8R^A9'\"B)7&C9G*D9W-E)_1EZ/4FZ;8"
	"GJK;H:W>I;#AI[/DJ[?HK;KJL+SML[_PM<'RN,3UN\\?XO<GZP,S]P\\__Q=(\"Q]0$"
	"RM8&S-D)S]L+T-T-T]`0U>(2U^04V>86V^D8W>L:X.P<X>\\>Y.`@Y?(CY_4DZ?8F"
	"Z_@I[?HJ[_LL\\?XN\\_\\P]@(Q]P,S^04U^@<W_0DX_@HZ_`P\\`@T]``\\`````````"
	"66678&R=9G*C:W>H<7VN=H&S>H:W?XN\\@X^_AI+#BY?'CIO,DI[/E:+2F:76G*C9"
	"GZS=HZ_@IK+BJ;7FJ[?IKKKKLKWNM,#QM\\/TN<;WO,CYO\\O\\P<W^P\\`!QM,#R-8%"
	"R]@(S=H*S]T,T=X/U.$0UN(2V.45VN<7W>H9WNL;X>T=X^\\?Y/$AYO0CZ/4EZO<G"
	"[/DI[OLK[_TM\\OXN]/`P]@(R]`0T^@8V^P@W_0DZ_PL[`0T\\`@X_`P`_````````"
	"7&B98VZ?:'2E;GJJ<W^O=X2U?(BY@8R]A)'\"B)3&C9C*D)S-DY_1EZ/4FJ;7G:K;"
	"H:W>I+#AI[/DJK;GK;GJL+SMLK_PM<'RN,3UNL;XOLGZP,O\\PL[_Q-$!Q]0$R=8&"
	"S-D)SML+T-T-TM\\0U>$2U^03V>46V^@8W>H:X.P<X>X>X^`@Y?(BY_0DZ?8FZ_@H"
	"[?HJ[OLL\\/TN\\_\\O]@$R]P,S^04U^P<W^`@X_@HZ_PP\\`0T^`P\\_````````````"
	"7VN<97&B:W:H<'RM=8&R>86V?HJ[@H^`AI+#BY;(CIK+DIW/E:'2F:75G*C9GZS="
	"HJ[?I;'BJ;3FK+CHKKKKL;WNM,#QM\\/SN<;WO,?YOLK[P<W^P\\`!QM,#R-4%R]@'"
	"S=D*S]P,T=X.T]`1U>(3V.45VN87W.D9WNL;X.T=XN\\?Y/$AYO,CZ/4EZO<GZ_DI"
	"[OLK\\/PM\\OXN\\`$Q]@(R]`0T^@8V^P<W_0DY_PL[_`P\\`@X^````````````````"
	"8FZ?:'2D;7FJ<GZO=X.T?(>Y@(R]A)#!B)3%C)C)CYS,E)_0EJ+4FZ;8GJK;H*S="
	"H[#AI[/DJ;;GK+CIL+OLLK[OM<'RN,3TNL;WO,CYO\\S\\PL[_Q-(\"Q]0$R=8&S-@("
	"S=L+T-T-TM\\/U>(2U^03V>86V^<8W.H:W^P<X>X>X^`@Y/(BY_0DZ/8FZ_@G[/DI"
	"[OPL\\/TN\\_\\P]0$Q]P(R]`4U^@<V^`@Y_@HY_PL[`0T^`P\\_````````````````"
	"97&B:G:H<'NL=(\"R>86W?HJZ@HZ_AI+#BI;'C9K+DIW/E:'2F:35G*C9GZO;HJ[?"
	"I;+BJ;3EJ[?HKKKKL+SMM,#PM\\+SN<7VO,CXOLO[P<W]P\\_`QM(#R-0%RM<'S-H*"
	"S]L,T=X.U-`0U>,2V.05VN<7V^D9WNL;X.T=XN\\>X_$AYO,BZ/4EZO8G[/DH[?LK"
	"\\/PM\\?\\O\\_`P]@(R]`0S^04U^P@W_0DY_PL[_`T\\`@\\^```_````````````````"
	":'2E;'BJ<7ZN=X.T>X>X?XN\\A)#!AY/$C)C)CYS,DY_0EJ+4FJ77G:G:H*S>I*_A"
	"IK/DJ;;FK;CIK[OLLK[OM<'RM\\/TNL;WO<GZO\\O\\PLW_Q=$\"Q],#R=8&R]@(SMH+"
	"T-T,TM\\/U>$1UN,3V.86V^<7W>H:W^P<X>X=XN\\@Y?(BYO,DZ?8FZ_<G[/DI[OLK"
	"\\?TN\\O\\O]0$Q]P,S]`4T^@8V^`@X_@HZ_`P\\`0T]`P\\^````````````````````"
	":G:F;WNL=(\"R>(6V?8FZ@8V^AI'#BI;&C9G*D9W.E:'1F*35FZC8GZO;HJ[?I;'B"
	"J+3EJK?HK;KKL;WNM+_QML+SN<7VO,CYOLK[P<S^P\\_`Q=(\"R-0$RM<'S-D)S]L,"
	"T=X.T]`0U>,2U^05VN87W.@8WNH;X.T=X>X>Y/$@Y?(CZ/4EZ?<G[/@I[OHJ[_PM"
	"\\OXN\\_`P]@(R]`,S^04U^P<W^`DY_@L[_`P]`@X^`P\\_````````````````````"
	";'FI<GZO=H*S>X>X@(R\\A(^`AY/$BY?(CYO,DI[0EJ+3FJ;6G:G:H*S=I*_AIK+C"
	"JK7FK+CIK[OLL;[OM,'RN,/TNL;WO<GYO\\O\\P<W^Q-$!QM,#R=4%R]@(S=L*T-P-"
	"TM\\/U.$1U^03V.45VN<7W.D:WNP;X.T>XN`?Y?(AYO0DZ?4FZO<H[?HI[OLK\\/TM"
	"\\O\\O]0$P]P(S]`0T^@8W^`@W_@HY_`L[`0T]`P\\^````````````````````````"
	";GJK=(\"P>(6V?8FZ@8V^AI'\"B9;&C)G*D)W.E:#1F*35FZ?8GJO<H:W>I+'BJ+3E"
	"J[?GKKKKL+WML[_PML+SN<3UN\\?XOLK[P,W]P\\_`Q=(\"Q]4$RM8'S-D*SML+T=T."
	"T]`0U>(2U^05V><6V^@9WNL;X.P<X>\\?X_$AYO,BY_4EZO8GZ_DH[?LJ[_PL\\?XN"
	"\\_`P]@(R]P,T^04U^P<W_0@Y_PH[_`P\\`0X^```_````````````````````````"
	"<'VN=8&R>X:X?XJ\\@X^`AY/$BY?(CYO,DI_/E:+3F:76G:G:GZS=HZ_@IK+CJ;7F"
	"K+CIK[OKL;[NM,#QM\\/TNL;WO<CZO\\O[PL[^Q,`!QM0#R=4&R]@(S=H+S]P-TMX."
	"U.$1UN,3V.45VN@7W.D9W^L;X>T=X^\\?Y/$AYO,CZ?4EZO<G[/DI[OLK\\/TL\\O\\N"
	"]0$Q]@,R]`0T^@4V^`@W_0DZ_PL[_`P]`PX^`P``````````````````````````"
	"";
